// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKKYzCFxN8Og16wQY9e701ODwIvuXRhUA',
    appId: '1:635645933703:web:83f0632ab32f39ca2e6022',
    messagingSenderId: '635645933703',
    projectId: 'pml3e2-a1af5',
    authDomain: 'pml3e2-a1af5.firebaseapp.com',
    databaseURL: 'https://pml3e2-a1af5-default-rtdb.firebaseio.com',
    storageBucket: 'pml3e2-a1af5.firebasestorage.app',
    measurementId: 'G-ZQESP5N2WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkyn0Ihp7MkqkOOoXFo-47FWH5Jj51ttE',
    appId: '1:635645933703:android:184cce98acb33fff2e6022',
    messagingSenderId: '635645933703',
    projectId: 'pml3e2-a1af5',
    databaseURL: 'https://pml3e2-a1af5-default-rtdb.firebaseio.com',
    storageBucket: 'pml3e2-a1af5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Frs-EfiCeGaNByJ7Z0IKCjBFdRo-jRQ',
    appId: '1:635645933703:ios:05a1633674320a5b2e6022',
    messagingSenderId: '635645933703',
    projectId: 'pml3e2-a1af5',
    databaseURL: 'https://pml3e2-a1af5-default-rtdb.firebaseio.com',
    storageBucket: 'pml3e2-a1af5.firebasestorage.app',
    iosBundleId: 'com.example.suratMobileSukorame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Frs-EfiCeGaNByJ7Z0IKCjBFdRo-jRQ',
    appId: '1:635645933703:ios:05a1633674320a5b2e6022',
    messagingSenderId: '635645933703',
    projectId: 'pml3e2-a1af5',
    databaseURL: 'https://pml3e2-a1af5-default-rtdb.firebaseio.com',
    storageBucket: 'pml3e2-a1af5.firebasestorage.app',
    iosBundleId: 'com.example.suratMobileSukorame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKKYzCFxN8Og16wQY9e701ODwIvuXRhUA',
    appId: '1:635645933703:web:85b418af65dcee102e6022',
    messagingSenderId: '635645933703',
    projectId: 'pml3e2-a1af5',
    authDomain: 'pml3e2-a1af5.firebaseapp.com',
    databaseURL: 'https://pml3e2-a1af5-default-rtdb.firebaseio.com',
    storageBucket: 'pml3e2-a1af5.firebasestorage.app',
    measurementId: 'G-GEVY1MR45P',
  );
}
