// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpgkS3UhWX7Tic3qoOvjrIos3kNv9TmgQ',
    appId: '1:524646525431:web:40d19cdd465670384366f2',
    messagingSenderId: '524646525431',
    projectId: 'aplikasi-surat-mobile',
    authDomain: 'aplikasi-surat-mobile.firebaseapp.com',
    storageBucket: 'aplikasi-surat-mobile.firebasestorage.app',
    measurementId: 'G-XGH7P0BTT6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZrvWGPhgTIwwyp1vDLSLTJWhBSLgcShI',
    appId: '1:524646525431:ios:2b96681080a292134366f2',
    messagingSenderId: '524646525431',
    projectId: 'aplikasi-surat-mobile',
    storageBucket: 'aplikasi-surat-mobile.firebasestorage.app',
    iosBundleId: 'com.example.suratMobileSukorame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZrvWGPhgTIwwyp1vDLSLTJWhBSLgcShI',
    appId: '1:524646525431:ios:2b96681080a292134366f2',
    messagingSenderId: '524646525431',
    projectId: 'aplikasi-surat-mobile',
    storageBucket: 'aplikasi-surat-mobile.firebasestorage.app',
    iosBundleId: 'com.example.suratMobileSukorame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpgkS3UhWX7Tic3qoOvjrIos3kNv9TmgQ',
    appId: '1:524646525431:web:a44b61057f405b064366f2',
    messagingSenderId: '524646525431',
    projectId: 'aplikasi-surat-mobile',
    authDomain: 'aplikasi-surat-mobile.firebaseapp.com',
    storageBucket: 'aplikasi-surat-mobile.firebasestorage.app',
    measurementId: 'G-X2N3G17PEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_fPn5fFhQhz9lFqcOQNcGoZEWIqMJGZE',
    appId: '1:524646525431:android:86af0dc2f0c7fab04366f2',
    messagingSenderId: '524646525431',
    projectId: 'aplikasi-surat-mobile',
    storageBucket: 'aplikasi-surat-mobile.firebasestorage.app',
  );

}